name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v[0-9].[0-9].[0-9]*'
      - 'v[0-9].[0-9].[0-9][0-9]*'
      - 'v[0-9].[0-9][0-9].[0-9]*'
      - 'v[0-9].[0-9][0-9].[0-9][0-9]*'
      - 'v[0-9][0-9].[0-9].[0-9]*'
      - 'v[0-9][0-9].[0-9].[0-9][0-9]*'
      - 'v[0-9][0-9].[0-9][0-9].[0-9]*'
      - 'v[0-9][0-9].[0-9][0-9].[0-9][0-9]*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-release:
    name: Build & Release
    runs-on: windows-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable-x86_64-pc-windows-msvc

#       - name: Install UPX
#         uses: crazy-max/ghaction-upx@v3
#         with:
#           install-only: true

      - name: Build Release
        run: cargo build --release

      - name: Get Version
        if: startsWith(github.ref, 'refs/tags/')
        id: get_version
        shell: pwsh
        run: |
          $version = $env:GITHUB_REF -replace "refs/tags/v", ""
          echo "VERSION=$version" >> $env:GITHUB_OUTPUT
          Write-Host "Version: $version"

      - name: Prepare Assets
        if: startsWith(github.ref, 'refs/tags/')
        shell: pwsh
        run: |
           $version = "${{ steps.get_version.outputs.VERSION }}"
           $raw_exe = "target/release/wsldashboard.exe"
           $versioned_exe = "target/release/wsldashboard.v$version.exe"
           # $upx_exe = "target/release/wsldashboard.v$version.upx.exe"
           
           # Rename original to versioned name (Uncompressed)
           Move-Item $raw_exe $versioned_exe
           
           # # Copy versioned to UPX target name
           # Copy-Item $versioned_exe $upx_exe

#       - name: Compress with UPX
#         if: startsWith(github.ref, 'refs/tags/')
#         run: upx --best --lzma target/release/wsldashboard.v${{ steps.get_version.outputs.VERSION }}.upx.exe

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/release/wsldashboard.v${{ steps.get_version.outputs.VERSION }}.exe
            # target/release/wsldashboard.v${{ steps.get_version.outputs.VERSION }}.upx.exe
          generate_release_notes: true
